project_id = "pobjadmnmfbeydqsymhx"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.get-signature-request]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.handle-email-events]
    verify_jwt = false
  [functions.send-lgt-report]
    verify_jwt = false
  [functions.submit-signature]
    verify_jwt = false
