import { ArrowLeft, ArrowRight, BookOpen, Clock3, Facebook, Linkedin, Link as LinkIcon, Twitter } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import vivekPhoto from '@/assets/vivek-doba.png';
import { Button } from '@/components/ui/button';
import { usePost, usePosts } from '@/hooks/usePublicContent';
import { usePublicCourses } from '@/hooks/useDbCourses';
import PublicSeo, { breadcrumbSchema, personSchema, SITE_URL } from '@/components/public/PublicSeo';

const makeId = (value: string) => value.toLowerCase().replace(/[^a-z0-9\s-]/g, '').trim().replace(/\s+/g, '-');
const headingsFrom = (body: string) => body.split('\n').filter(line => /^##\s+/.test(line)).map(line => ({ label: line.replace(/^##\s+/, '').trim(), id: makeId(line.replace(/^##\s+/, '')) }));
const readingTime = (body: string) => Math.max(1, Math.ceil(body.trim().split(/\s+/).filter(Boolean).length / 220));

export default function BlogPostPage() {
  const { slug } = useParams(); const { data: post, isLoading } = usePost(slug); const { data: posts = [] } = usePosts(); const { data: courses = [] } = usePublicCourses();
  if (isLoading) return <div className="mx-auto max-w-3xl px-4 py-20 text-muted-foreground">Loading article…</div>;
  if (!post) return <div className="mx-auto max-w-3xl px-4 py-20 text-center"><PublicSeo title="Article Not Found | Vivek Doba" description="The requested article could not be found." path={`/blog/${slug || 'article'}`} noindex /><BookOpen className="mx-auto h-10 w-10 text-primary" /><h1 className="mt-3 text-2xl font-bold">Article not found</h1><Link to="/blog" className="mt-4 inline-block text-primary">Return to Blog</Link></div>;
  const path = `/blog/${post.slug}`; const url = `${SITE_URL}${path}`; const description = post.seo_description || post.excerpt.slice(0, 160); const headings = headingsFrom(post.body); const course = courses.find(item => item.slug === post.related_course_slug); const related = posts.filter(item => item.id !== post.id && (item.category === post.category || item.tags.some(tag => post.tags.includes(tag)))).slice(0, 3);
  const articleSchema = { '@context': 'https://schema.org', '@type': 'Article', headline: post.title, description, datePublished: post.published_at, dateModified: post.updated_at, mainEntityOfPage: url, author: { '@id': `${SITE_URL}/#vivek-doba` }, publisher: { '@id': `${SITE_URL}/#organization` }, ...(post.cover_image ? { image: post.cover_image } : {}) };
  const share = [{ label: 'Share on LinkedIn', icon: Linkedin, href: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}` }, { label: 'Share on Facebook', icon: Facebook, href: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}` }, { label: 'Share on X', icon: Twitter, href: `https://twitter.com/intent/tweet?url=${encodeURIComponent(url)}&text=${encodeURIComponent(post.title)}` }];
  return <article><PublicSeo title={post.seo_title || `${post.title} | Vivek Doba`} description={description} path={path} image={post.cover_image || undefined} type="article" schemas={[personSchema, articleSchema, breadcrumbSchema([{ name: 'Home', path: '/' }, { name: 'Blog', path: '/blog' }, { name: post.title, path }])]} />
    <header className="border-b bg-muted/30 py-12 sm:py-16"><div className="mx-auto max-w-4xl px-4"><Link to="/blog" className="inline-flex items-center gap-1 text-sm font-semibold text-primary"><ArrowLeft className="h-4 w-4" />Back to Blog</Link><p className="mt-8 text-sm font-bold uppercase text-primary">{post.category}</p><h1 className="mt-3 text-4xl font-bold leading-tight sm:text-5xl">{post.title}</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">{post.excerpt}</p><div className="mt-6 flex items-center gap-3"><img src={vivekPhoto} alt="Vivek Doba" width="96" height="96" className="h-12 w-12 rounded-full object-cover" /><div><p className="font-bold">{post.author}</p><p className="flex items-center gap-1 text-sm text-muted-foreground"><Clock3 className="h-4 w-4" />{readingTime(post.body)} min read{post.published_at ? ` · ${new Date(post.published_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}` : ''}</p></div></div></div></header>
    {post.cover_image && <img src={post.cover_image} alt={post.title} width="1200" height="675" fetchPriority="high" className="mx-auto aspect-video w-full max-w-6xl object-cover" />}
    <div className="mx-auto grid max-w-6xl gap-10 px-4 py-12 lg:grid-cols-[220px_minmax(0,1fr)]">{headings.length > 0 && <aside><nav aria-label="Table of contents" className="sticky top-32 border-l-2 border-primary/30 pl-4"><p className="mb-3 font-bold">In this article</p><ul className="space-y-2 text-sm text-muted-foreground">{headings.map(item => <li key={item.id}><a href={`#${item.id}`} className="hover:text-primary">{item.label}</a></li>)}</ul></nav></aside>}<div className={headings.length ? '' : 'lg:col-start-2'}><div className="blog-markdown max-w-3xl text-[1.05rem] leading-8"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{ h2: ({ children }) => <h2 id={makeId(String(children))} className="mb-4 mt-10 scroll-mt-32 text-3xl font-bold">{children}</h2>, h3: ({ children }) => <h3 className="mb-3 mt-8 text-2xl font-bold">{children}</h3>, p: ({ children }) => <p className="my-5">{children}</p>, ul: ({ children }) => <ul className="my-5 list-disc space-y-2 pl-6">{children}</ul>, ol: ({ children }) => <ol className="my-5 list-decimal space-y-2 pl-6">{children}</ol>, a: ({ href, children }) => <a href={href} className="font-semibold text-primary underline">{children}</a> }}>{post.body}</ReactMarkdown></div>
      {course && <section className="mt-12 grid overflow-hidden rounded-md border bg-card sm:grid-cols-[180px_1fr]">{course.cardImageUrl && <img src={course.cardImageUrl} alt={course.name} width="600" height="450" loading="lazy" className="h-full min-h-40 w-full object-cover" />}<div className="p-6"><p className="text-xs font-bold uppercase text-primary">Program related to this article</p><h2 className="mt-2 text-2xl font-bold">{course.name}</h2><p className="mt-2 text-muted-foreground">{course.outcome}</p><Button asChild variant="outline" className="mt-5"><Link to={`/courses/${course.slug}`}>See the program <ArrowRight className="h-4 w-4" /></Link></Button></div></section>}
      <div className="mt-10 flex items-center gap-2 border-y py-5"><span className="mr-2 text-sm font-bold">Share</span>{share.map(item => <Button key={item.label} asChild variant="outline" size="icon"><a href={item.href} target="_blank" rel="noopener noreferrer" aria-label={item.label}><item.icon className="h-4 w-4" /></a></Button>)}<Button variant="outline" size="icon" aria-label="Copy article link" onClick={() => navigator.clipboard.writeText(url)}><LinkIcon className="h-4 w-4" /></Button></div>
    </div></div>
    {related.length > 0 && <section className="border-t bg-muted/30 py-14"><div className="mx-auto max-w-6xl px-4"><h2 className="text-3xl font-bold">Related articles</h2><div className="mt-7 grid gap-5 md:grid-cols-3">{related.map(item => <Link key={item.id} to={`/blog/${item.slug}`} className="rounded-md border bg-card p-5"><span className="text-xs font-bold text-primary">{item.category}</span><h3 className="mt-2 font-bold">{item.title}</h3><p className="mt-2 text-sm text-muted-foreground">{item.excerpt}</p></Link>)}</div></div></section>}
  </article>;
}