import { ArrowRight, BookOpen, CalendarDays } from 'lucide-react';
import { Link } from 'react-router-dom';
import PageBanner from '@/components/public/PageBanner';
import { useBlogPosts } from '@/hooks/usePublicContent';
import PublicSeo, { breadcrumbSchema } from '@/components/public/PublicSeo';

export default function BlogPage() {
  const { data = [], isLoading } = useBlogPosts();
  return <><PublicSeo title="Blog | Business, Health & Family Balance | Vivek Doba" description="Practical articles for business owners on growth, leadership, mindset, health and family, rooted in Indian wisdom." path="/blog" schemas={[breadcrumbSchema([{ name: 'Home', path: '/' }, { name: 'Blog', path: '/blog' }])]} /><PageBanner icon={BookOpen} eyebrow="Blog" title="Ideas for conscious growth" description="Reflections and practical guidance for purpose, leadership, relationships and prosperity." /><section className="max-w-6xl mx-auto px-4 py-14">{isLoading ? <p className="text-muted-foreground">Loading articles…</p> : data.length === 0 ? <div className="border border-dashed border-primary/40 p-10 text-center"><BookOpen className="w-10 h-10 text-primary mx-auto mb-3" /><h2 className="text-xl font-bold">Insights are on the way</h2><p className="text-sm text-muted-foreground mt-2">Published articles will appear here.</p></div> : <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{data.map(post => <article key={post.id} className="bg-card border border-border rounded-lg overflow-hidden flex flex-col">{post.cover_image_url ? <img src={post.cover_image_url} alt={post.title} width="960" height="540" loading="lazy" className="aspect-[16/9] object-cover" /> : <div className="aspect-[16/9] gradient-saffron flex items-center justify-center"><BookOpen className="w-10 h-10 text-primary-foreground/80" /></div>}<div className="p-5 flex flex-col flex-1"><span className="text-xs text-muted-foreground flex items-center gap-1"><CalendarDays className="w-3.5 h-3.5" />{new Date(post.published_at || post.created_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</span><h2 className="text-xl font-bold mt-3">{post.title}</h2><p className="text-sm text-muted-foreground my-3 flex-1">{post.excerpt || post.content.slice(0, 130)}</p><Link to={`/blog/${post.slug}`} className="text-primary font-semibold text-sm flex items-center gap-1">Read More <ArrowRight className="w-4 h-4" /></Link></div></article>)}</div>}</section></>;
}