import { FormEvent, useState } from 'react';
import { Mail, MapPin, MessageSquare, Phone } from 'lucide-react';
import { toast } from 'sonner';
import PageBanner from '@/components/public/PageBanner';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';

export default function ContactPage() {
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ name: '', email: '', phone: '', message: '' });
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); const { error } = await supabase.from('contact_submissions').insert(form); setSaving(false); if (error) { toast.error('Your message could not be sent. Please try WhatsApp.'); return; } toast.success('Thank you. We will contact you soon.'); setForm({ name: '', email: '', phone: '', message: '' }); };
  const set = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }));
  return <><PageBanner icon={Phone} eyebrow="Contact Us" title="Begin a meaningful conversation" description="Tell us what you are seeking. Our team will help you find the right first step." /><section className="max-w-6xl mx-auto px-4 py-14 grid lg:grid-cols-[1fr_1.2fr] gap-10"><div><h2 className="text-2xl font-bold mb-5">We are here to help</h2><div className="space-y-5 text-sm"><a href="tel:9607050111" className="flex gap-3"><Phone className="w-5 h-5 text-primary shrink-0" /><span><strong className="block">Phone</strong>9607050111</span></a><a href="mailto:info@vivekdoba.com" className="flex gap-3"><Mail className="w-5 h-5 text-primary shrink-0" /><span><strong className="block">Email</strong>info@vivekdoba.com</span></a><a href="https://wa.me/919607050111" target="_blank" rel="noopener noreferrer" className="flex gap-3"><MessageSquare className="w-5 h-5 text-primary shrink-0" /><span><strong className="block">WhatsApp</strong>Chat with our team</span></a><div className="flex gap-3"><MapPin className="w-5 h-5 text-primary shrink-0" /><span><strong className="block">Visit us</strong>Office No. 228 &amp; 229, Tower B, Second Floor, Gera Imperium Gateway, Near Nashik Phata Metro Station, Nashik Phata, Pune 411034</span></div></div><iframe title="Vivek Doba Business Mastery location" className="w-full h-64 mt-8 border border-border rounded-lg" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src="https://www.google.com/maps?q=Gera%20Imperium%20Gateway%20Nashik%20Phata%20Pune%20411034&output=embed" /></div><form onSubmit={submit} className="bg-card border border-border rounded-lg p-6 sm:p-8 space-y-5"><h2 className="text-2xl font-bold">Send a message</h2><div><label className="text-sm font-medium" htmlFor="contact-name">Name *</label><Input id="contact-name" required minLength={2} maxLength={100} value={form.name} onChange={e => set('name', e.target.value)} /></div><div className="grid sm:grid-cols-2 gap-4"><div><label className="text-sm font-medium" htmlFor="contact-email">Email *</label><Input id="contact-email" required type="email" maxLength={254} value={form.email} onChange={e => set('email', e.target.value)} /></div><div><label className="text-sm font-medium" htmlFor="contact-phone">Phone</label><Input id="contact-phone" type="tel" maxLength={30} value={form.phone} onChange={e => set('phone', e.target.value)} /></div></div><div><label className="text-sm font-medium" htmlFor="contact-message">Message *</label><Textarea id="contact-message" required minLength={5} maxLength={3000} rows={7} value={form.message} onChange={e => set('message', e.target.value)} /></div><Button type="submit" disabled={saving} className="w-full gradient-saffron border-0">{saving ? 'Sending…' : 'Send Message'}</Button></form></section></>;
}