import { FormEvent, useMemo, useState } from 'react';
import { Clock3, Mail, MapPin, MessageCircle, Phone } from 'lucide-react';
import { z } from 'zod';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';
import type { Database } from '@/integrations/supabase/types';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { usePublicCourses } from '@/hooks/useDbCourses';
import PublicSeo, { breadcrumbSchema, BUSINESS_ADDRESS, BUSINESS_EMAIL, BUSINESS_HOURS, BUSINESS_NAME, BUSINESS_PHONE, professionalServiceSchema } from '@/components/public/PublicSeo';

const whatsappMessage = 'Namaste, I would like to speak with Vivek Doba’s team.';
const whatsappUrl = `https://wa.me/91${BUSINESS_PHONE}?text=${encodeURIComponent(whatsappMessage)}`;
const directionsUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(BUSINESS_ADDRESS)}`;
const turnoverOptions = ['Under ₹50 lakh', '₹50 lakh–₹2 crore', '₹2–15 crore', 'Above ₹15 crore'] as const;
const contactSchema = z.object({
  name: z.string().trim().min(2, 'Please enter your name.').max(100),
  phone: z.string().trim().regex(/^[+\d][\d\s()-]{7,19}$/, 'Please enter a valid phone number.'),
  email: z.string().trim().email('Please enter a valid email address.').max(254),
  business_type: z.string().trim().min(2, 'Please enter your business type.').max(120),
  annual_turnover_range: z.enum(turnoverOptions),
  program_interest: z.string().trim().min(1, 'Please choose a program.').max(180),
  message: z.string().trim().min(5, 'Please add a short message.').max(3000),
});
const faqItems = [
  { question: 'How soon will you reply?', answer: 'Our team will respond as soon as possible during business hours.' },
  { question: 'Can I visit without an appointment?', answer: 'Please call or WhatsApp before visiting so the team can confirm that someone is available to meet you.' },
  { question: 'Do you coach online?', answer: 'Selected programs and one-to-one coaching may be available online. Tell us what you need and the team will confirm the suitable option.' },
];
const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqItems.map(item => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };

export default function ContactPage() {
  const { data: courses = [] } = usePublicCourses();
  const initial = useMemo(() => ({ name: '', phone: '', email: '', business_type: '', annual_turnover_range: '', program_interest: '', message: '' }), []);
  const [form, setForm] = useState(initial); const [saving, setSaving] = useState(false); const [success, setSuccess] = useState(false);
  const set = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); const parsed = contactSchema.safeParse(form); if (!parsed.success) { toast.error(parsed.error.issues[0]?.message || 'Please check the form.'); return; } setSaving(true); const id = crypto.randomUUID(); const submission: Database['public']['Tables']['contact_submissions']['Insert'] = { id, name: parsed.data.name, phone: parsed.data.phone, email: parsed.data.email, business_type: parsed.data.business_type, annual_turnover_range: parsed.data.annual_turnover_range, program_interest: parsed.data.program_interest, message: parsed.data.message }; const { error } = await supabase.from('contact_submissions').insert(submission); if (error) { setSaving(false); toast.error('Your enquiry could not be saved. Please use WhatsApp or call us.'); return; } setSuccess(true); setForm(initial); const { error: notificationError } = await supabase.functions.invoke('notify-contact-submission', { body: { submission_id: id } }); setSaving(false); if (notificationError) console.error('Contact notification failed after the enquiry was saved.'); };
  return <main className="bg-background"><PublicSeo title="Contact Vivek Doba | Business Coach in Pune" description="Call, WhatsApp, email or visit Vivek Doba Business Mastery in Pimpri-Chinchwad, Pune. Ask about business coaching and programs." path="/contact" schemas={[professionalServiceSchema, faqSchema, breadcrumbSchema([{ name: 'Home', path: '/' }, { name: 'Contact', path: '/contact' }])]} />
    <section className="border-b bg-muted/30 py-14 sm:py-20"><div className="mx-auto max-w-6xl px-4"><p className="font-course-serif text-lg italic text-primary">Call, write or visit</p><h1 className="mt-3 max-w-4xl text-4xl font-bold leading-tight sm:text-5xl">Contact Vivek Doba: Business Coach in Pimpri-Chinchwad, Pune</h1><p className="mt-5 max-w-2xl text-lg text-muted-foreground">Tell us what is happening in your business. We will help you identify a useful next step.</p></div></section>
    <section className="mx-auto grid max-w-6xl gap-4 px-4 py-10 md:grid-cols-3"><a href={`tel:${BUSINESS_PHONE}`} className="rounded-md border bg-card p-6 transition-shadow hover:shadow-md"><Phone className="h-8 w-8 text-primary" /><h2 className="mt-4 text-xl font-bold">Call {BUSINESS_PHONE}</h2><p className="mt-2 text-sm text-muted-foreground">Speak directly with the team.</p></a><a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className="rounded-md border bg-card p-6 transition-shadow hover:shadow-md"><MessageCircle className="h-8 w-8 text-primary" /><h2 className="mt-4 text-xl font-bold">WhatsApp</h2><p className="mt-2 text-sm text-muted-foreground">Start with a short message.</p></a><a href={`mailto:${BUSINESS_EMAIL}`} className="rounded-md border bg-card p-6 transition-shadow hover:shadow-md"><Mail className="h-8 w-8 text-primary" /><h2 className="mt-4 text-xl font-bold">Email {BUSINESS_EMAIL}</h2><p className="mt-2 text-sm text-muted-foreground">Send the details in your own time.</p></a></section>
    <section className="mx-auto grid max-w-6xl gap-10 px-4 pb-16 lg:grid-cols-[1fr_1.15fr]"><div><h2 className="text-3xl font-bold">Visit us</h2><div className="mt-6 space-y-5 text-sm leading-6"><div className="flex gap-3"><MapPin className="mt-1 h-5 w-5 shrink-0 text-primary" /><div><strong className="block">{BUSINESS_NAME}</strong><span>{BUSINESS_ADDRESS}</span></div></div><a href={`tel:${BUSINESS_PHONE}`} className="flex gap-3"><Phone className="h-5 w-5 shrink-0 text-primary" /><span><strong className="block">Phone</strong>{BUSINESS_PHONE}</span></a>{BUSINESS_HOURS && <div className="flex gap-3"><Clock3 className="h-5 w-5 shrink-0 text-primary" /><span><strong className="block">Opening hours</strong>{BUSINESS_HOURS}</span></div>}</div><iframe title={`${BUSINESS_NAME} location`} className="mt-7 h-72 w-full rounded-md border" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src={`https://www.google.com/maps?q=${encodeURIComponent(BUSINESS_ADDRESS)}&output=embed`} /><Button asChild variant="outline" className="mt-4"><a href={directionsUrl} target="_blank" rel="noopener noreferrer"><MapPin className="h-4 w-4" />Get directions</a></Button></div>
      <form onSubmit={submit} className="space-y-5 rounded-md border bg-card p-6 sm:p-8" noValidate><div><h2 className="text-3xl font-bold">Tell us about your business</h2><p className="mt-2 text-sm text-muted-foreground">Fields marked * are required.</p></div>{success && <div role="status" className="rounded-md border border-primary/30 bg-primary/10 p-4 font-semibold">Thank you. We will call you soon.</div>}<div className="grid gap-4 sm:grid-cols-2"><label className="space-y-1 text-sm font-medium">Name *<Input required maxLength={100} autoComplete="name" value={form.name} onChange={event => set('name', event.target.value)} /></label><label className="space-y-1 text-sm font-medium">Phone *<Input required type="tel" maxLength={20} autoComplete="tel" value={form.phone} onChange={event => set('phone', event.target.value)} /></label></div><label className="block space-y-1 text-sm font-medium">Email *<Input required type="email" maxLength={254} autoComplete="email" value={form.email} onChange={event => set('email', event.target.value)} /></label><label className="block space-y-1 text-sm font-medium">Business type *<Input required maxLength={120} placeholder="For example, manufacturing or professional services" value={form.business_type} onChange={event => set('business_type', event.target.value)} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-1 text-sm font-medium">Annual turnover range *<Select value={form.annual_turnover_range} onValueChange={value => set('annual_turnover_range', value)}><SelectTrigger><SelectValue placeholder="Choose a range" /></SelectTrigger><SelectContent>{turnoverOptions.map(option => <SelectItem key={option} value={option}>{option}</SelectItem>)}</SelectContent></Select></label><label className="space-y-1 text-sm font-medium">Which program interests you? *<Select value={form.program_interest} onValueChange={value => set('program_interest', value)}><SelectTrigger><SelectValue placeholder="Choose a program" /></SelectTrigger><SelectContent>{courses.map(course => <SelectItem key={course.slug} value={course.name}>{course.name}</SelectItem>)}</SelectContent></Select></label></div><label className="block space-y-1 text-sm font-medium">Message *<Textarea required minLength={5} maxLength={3000} rows={6} value={form.message} onChange={event => set('message', event.target.value)} /></label><Button type="submit" className="w-full" disabled={saving}>{saving ? 'Sending…' : 'Send enquiry'}</Button></form></section>
    <section className="border-t bg-muted/30 py-14"><div className="mx-auto max-w-3xl px-4"><h2 className="text-3xl font-bold">Frequently asked questions</h2><Accordion type="single" collapsible className="mt-6 border-t">{faqItems.map((item, index) => <AccordionItem key={item.question} value={`contact-${index}`}><AccordionTrigger className="text-left">{item.question}</AccordionTrigger><AccordionContent className="leading-6 text-muted-foreground">{item.answer}</AccordionContent></AccordionItem>)}</Accordion></div></section>
  </main>;
}