import { Link, useParams } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, Check, ChevronRight, Clock3, MapPin, MessageCircle, Users } from 'lucide-react';
import NotFound from '@/pages/NotFound';
import { Button } from '@/components/ui/button';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { CourseCta, CoursePrice } from '@/components/public/CourseElements';
import { CourseSeo, courseSchema } from '@/components/public/CourseSeo';
import { formatINR, gstAmount, totalWithGst, whatsappLink, type Course } from '@/data/courses';
import { usePublicCourses } from '@/hooks/useDbCourses';
import { openExternal } from '@/lib/openExternal';

const reveal = { initial: { opacity: 0, y: 22 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: .15 }, transition: { duration: .55 } };

function buildFaqs(course: Course) {
  const fee = course.priceINR === 0 ? 'This program is free.' : course.priceINR === null ? `${course.priceNote}.` : `${course.priceFrom ? 'Fees start from ' : 'The fee is '}${formatINR(course.priceINR)}${course.gstApplies ? ' plus 18% GST.' : ', inclusive of all taxes.'}`;
  return [
    { question: `How long is ${course.name}?`, answer: course.duration },
    { question: 'Is it online or offline?', answer: `${course.format}. ${course.mode}.` },
    { question: 'Who is it for?', answer: course.forWhom },
    { question: 'What is the fee?', answer: fee },
    { question: 'How do I join?', answer: 'Tap the button on this page. It opens WhatsApp with your message ready.' },
  ];
}

function Hero({ course }: { course: Course }) {
  return <section className={`course-hero-texture border-b px-4 py-12 sm:py-20 ${course.slug === 'ram-nirvana' ? 'bg-course-maroon text-primary-foreground' : 'border-primary/15 bg-course-ivory'}`}>
    <div className="mx-auto max-w-6xl"><nav aria-label="Breadcrumb" className={`flex flex-wrap items-center gap-1 text-xs ${course.slug === 'ram-nirvana' ? 'text-primary-foreground/70' : 'text-muted-foreground'}`}><Link to="/">Home</Link><ChevronRight className="h-3 w-3" /><Link to="/courses">Courses</Link><ChevronRight className="h-3 w-3" /><span>{course.name}</span></nav>
       <div className="mt-8 grid items-center gap-8 lg:grid-cols-[1fr_.9fr]"><div><p className={`text-xs font-semibold uppercase ${course.slug === 'ram-nirvana' ? 'text-primary-foreground/70' : 'text-course-saffron'}`}>{course.step ? `Step ${course.step} · ` : ''}{course.stage}</p><p className="font-course-serif mt-4 text-3xl italic leading-tight sm:text-5xl">“{course.hook}”</p><h1 className="mt-5 text-3xl font-bold sm:text-5xl">{course.name}</h1><p className={`mt-5 max-w-3xl text-lg font-medium leading-8 ${course.slug === 'ram-nirvana' ? 'text-primary-foreground/85' : 'text-muted-foreground'}`}>{course.outcome}</p>{course.invitationNote && <p className="mt-5 max-w-3xl border-l-4 border-course-saffron bg-card/80 px-5 py-4 font-semibold leading-7 text-foreground">{course.invitationNote}</p>}</div>{course.heroImageUrl && <img src={course.heroImageUrl} alt={`${course.name}: ${course.outcome}`} className="aspect-video w-full rounded-lg object-cover shadow-course" />}</div>
      <div className={`mt-9 flex flex-wrap gap-3 rounded-[18px] border p-4 ${course.slug === 'ram-nirvana' ? 'border-primary-foreground/20 bg-primary-foreground/10' : 'border-primary/15 bg-card/80'}`}><span className="inline-flex items-center gap-2"><Clock3 className="h-4 w-4" />{course.duration}</span><span>· {course.format}</span><span>· {course.mode}</span>{course.seats && <span className="inline-flex items-center gap-2">· <Users className="h-4 w-4" />{course.seats}</span>}{course.nextDate && <span>· {course.nextDate}</span>}</div>
      {course.slug !== 'ram-nirvana' && <div className="mt-8 flex flex-wrap items-center gap-4"><CoursePrice course={course} /><CourseCta course={course} />{!course.locked && <Button variant="outline" className="min-h-12" onClick={() => openExternal(whatsappLink(course.name))}><MessageCircle />Ask on WhatsApp</Button>}{course.locked && <p className="font-semibold">Open to Life’s Golden Triangle graduates, by invitation.</p>}</div>}
    </div>
  </section>;
}

export default function CourseDetailPage() {
  const { slug = '' } = useParams();
  const { data: courses = [] } = usePublicCourses();
  const course = courses.find(item => item.slug === slug);
  if (!course) return <NotFound />;
  const faqs = buildFaqs(course);
  if (course.slug === 'ram-nirvana') return <div><CourseSeo title={course.seo.title} description={course.seo.description} path={`/courses/${course.slug}`} image={course.heroImageUrl} schema={courseSchema(course, faqs)} /><Hero course={course} /><section className="bg-course-maroon px-4 pb-20 text-primary-foreground"><motion.div {...reveal} className="mx-auto max-w-3xl rounded-[18px] border border-primary-foreground/20 bg-primary-foreground/10 p-7 text-center sm:p-12"><div className="text-6xl" aria-hidden="true">ॐ</div><h2 className="mt-5 text-3xl font-bold">A vision · After 2029</h2><p className="mt-5 text-lg leading-8 text-primary-foreground/85">{course.outcome} A future home for people ready to bring business, health and family into balance.</p><Button className="mt-7 min-h-12 bg-primary text-primary-foreground hover:bg-primary/90" onClick={() => openExternal(whatsappLink(course.name))}>Talk to us<MessageCircle /></Button></motion.div></section></div>;
  const next = course.nextSlug ? courses.find(item => item.slug === course.nextSlug) : undefined;
  return <div className="bg-course-ivory pb-20 md:pb-0">
    <CourseSeo title={course.seo.title} description={course.seo.description} path={`/courses/${course.slug}`} image={course.heroImageUrl} schema={courseSchema(course, faqs)} />
    <Hero course={course} />
    {course.before.length > 0 && course.after.length > 0 && <motion.section {...reveal} className="mx-auto max-w-6xl px-4 py-16"><h2 className="text-3xl font-bold">From where you are, to where you could be</h2><div className="mt-8 grid items-stretch gap-4 md:grid-cols-[1fr_auto_1fr]"><div className="rounded-[18px] bg-muted p-6"><h3 className="text-xl font-bold text-muted-foreground">Today</h3><ul className="mt-4 space-y-3 text-muted-foreground">{course.before.map(item => <li key={item}>— {item}</li>)}</ul></div><ArrowRight className="m-auto hidden h-8 w-8 text-course-saffron md:block" /><div className="rounded-[18px] border border-course-saffron bg-card p-6 shadow-course"><h3 className="text-xl font-bold text-course-saffron">After {course.duration}</h3><ul className="mt-4 space-y-3">{course.after.map(item => <li key={item} className="flex gap-2"><Check className="mt-1 h-4 w-4 shrink-0 text-course-saffron" />{item}</li>)}</ul></div></div></motion.section>}
    <motion.section {...reveal} className="border-y border-primary/15 bg-background px-4 py-16"><div className="mx-auto grid max-w-6xl gap-8 md:grid-cols-2"><div><h2 className="text-3xl font-bold">Is this for you?</h2><blockquote className="font-course-serif mt-6 border-l-4 border-course-saffron pl-5 text-3xl italic leading-tight text-course-maroon">{course.forWhom}</blockquote></div>{course.notFor.length > 0 && <div className="rounded-[18px] bg-muted p-6"><h3 className="text-xl font-bold">This is not for you if…</h3><ul className="mt-4 space-y-3 text-muted-foreground">{course.notFor.map(item => <li key={item}>— {item}</li>)}</ul></div>}</div></motion.section>
    {(course.benefits?.length || 0) > 0 && <motion.section {...reveal} className="border-y border-primary/15 bg-background px-4 py-16"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-bold">What this changes for you</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{course.benefits?.map(item => <article key={item.title} className="border-l-4 border-course-saffron bg-card p-6 shadow-course"><h3 className="text-xl font-bold">{item.title}</h3><p className="mt-3 leading-7 text-muted-foreground">{item.text}</p></article>)}</div></div></motion.section>}
    {(course.method?.length || 0) > 0 && <motion.section {...reveal} className="mx-auto max-w-4xl px-4 py-16"><h2 className="text-3xl font-bold">How the program works</h2><ol className="mt-8 space-y-6 border-l-2 border-course-saffron pl-7">{course.method?.map((item,index) => <li key={item.title} className="relative"><span className="absolute -left-10 flex h-6 w-6 items-center justify-center rounded-full bg-course-saffron text-xs font-bold text-primary-foreground">{index+1}</span><h3 className="text-xl font-bold">{item.title}</h3><p className="mt-2 leading-7 text-muted-foreground">{item.text}</p></li>)}</ol></motion.section>}
    {course.journey.length > 0 && <motion.section {...reveal} className="mx-auto max-w-4xl px-4 py-16"><h2 className="text-3xl font-bold">What Happens Inside {course.name}</h2><div className="mt-9 border-l-2 border-course-saffron pl-7">{course.journey.map((item,index) => <article key={item.title} className="relative pb-9 last:pb-0"><span className="absolute -left-[2.2rem] top-0 flex h-5 w-5 items-center justify-center rounded-full bg-course-saffron text-[10px] font-bold text-primary-foreground">{index+1}</span><h3 className="text-xl font-bold">{item.title}</h3><p className="mt-2 leading-7 text-muted-foreground">{item.text}</p></article>)}</div></motion.section>}
    {course.takeaways.length > 0 && <motion.section {...reveal} className="border-y border-primary/15 bg-background px-4 py-16"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-bold">Your Outcomes</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{course.takeaways.map(item => <div key={item} className="rounded-[18px] border border-primary/15 bg-card p-5 shadow-course"><Check className="h-6 w-6 text-course-saffron" /><p className="mt-3 font-semibold leading-7">{item}</p></div>)}</div></div></motion.section>}
    {course.videos.length > 0 && <motion.section {...reveal} className="mx-auto max-w-6xl px-4 py-16"><h2 className="text-3xl font-bold">Stories from Participants</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{course.videos.map(video => <figure key={video.youtubeId}><iframe className="aspect-video w-full rounded-[18px]" loading="lazy" src={`https://www.youtube-nocookie.com/embed/${video.youtubeId}`} title={`${video.name} shares their ${course.name} experience`} allowFullScreen /><figcaption className="mt-2 font-semibold">{video.name}{video.business ? ` · ${video.business}` : ''}</figcaption></figure>)}</div></motion.section>}
    <motion.section {...reveal} className="mx-auto max-w-4xl px-4 py-16"><h2 className="text-3xl font-bold">Your Investment</h2><div className="mt-8 rounded-[18px] border border-primary/15 bg-card p-6 shadow-course sm:p-9"><CoursePrice course={course} />{typeof course.priceINR === 'number' && course.priceINR > 0 && course.gstApplies && <dl className="mt-6 divide-y border-y"><div className="flex justify-between py-3"><dt>Program fee</dt><dd>{course.priceFrom ? 'From ' : ''}{formatINR(course.priceINR)}</dd></div><div className="flex justify-between py-3"><dt>GST (18%)</dt><dd>{formatINR(gstAmount(course.priceINR))}</dd></div><div className="flex justify-between py-3 font-bold"><dt>{course.priceFrom ? 'Starting total' : 'Total'}</dt><dd>{formatINR(totalWithGst(course.priceINR))}</dd></div></dl>}{course.priceINR === null && <p className="mt-3 text-muted-foreground">Every journey is different. We share the fee after we understand your business.</p>}<div className="mt-6 space-y-2 text-sm"><p><strong>Duration:</strong> {course.duration}</p>{course.seats && <p><strong>Places:</strong> {course.seats}</p>}{course.nextDate && <p><strong>Next date:</strong> {course.nextDate}</p>}</div>{!course.locked && <div className="mt-6"><CourseCta course={course} /></div>}{course.locked && <p className="mt-6 font-semibold">Open to Life’s Golden Triangle graduates, by invitation.</p>}{course.gstApplies && <p className="mt-5 text-xs text-muted-foreground">A GST invoice is issued for every enrollment.</p>}</div></motion.section>
    <motion.section {...reveal} className="border-y border-primary/15 bg-background px-4 py-16"><div className="mx-auto max-w-4xl"><h2 className="text-3xl font-bold">Questions about {course.name}</h2><Accordion type="single" collapsible className="mt-7">{faqs.map((item,index) => <AccordionItem key={item.question} value={`${index}`}><AccordionTrigger className="text-left">{item.question}</AccordionTrigger><AccordionContent className="leading-7 text-muted-foreground">{item.answer}</AccordionContent></AccordionItem>)}</Accordion></div></motion.section>
    {next && <motion.section {...reveal} className="mx-auto max-w-5xl px-4 py-16"><div className="rounded-[18px] bg-course-maroon p-7 text-primary-foreground shadow-course sm:p-10"><p className="text-sm font-semibold uppercase text-primary-foreground/70">Your next step after this · {next.stage}</p><h2 className="font-course-serif mt-3 text-4xl font-semibold italic">{next.name}</h2><p className="font-course-serif mt-4 text-2xl italic">“{next.hook}”</p><p className="mt-3 max-w-3xl text-primary-foreground/80">{next.outcome}</p><div className="mt-6 flex flex-wrap gap-4"><Button asChild className="min-h-12 bg-primary text-primary-foreground"><Link to={`/courses/${next.slug}`}>See the next step<ArrowRight /></Link></Button><Button asChild variant="link" className="min-h-12 text-primary-foreground"><Link to="/courses">See the whole ladder</Link></Button></div></div></motion.section>}
    {!course.locked && <div className="fixed inset-x-0 bottom-0 z-40 flex items-center justify-between gap-3 border-t bg-background/95 px-4 py-3 shadow-2xl backdrop-blur md:hidden"><CoursePrice course={course} /><CourseCta course={course} /></div>}
  </div>;
}
