import { useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ChevronLeft, ChevronRight, ExternalLink, Image as ImageIcon, Play, X } from 'lucide-react';
import { useGallery, type GalleryItem } from '@/hooks/usePublicContent';
import { Button } from '@/components/ui/button';
import PublicSeo, { breadcrumbSchema } from '@/components/public/PublicSeo';

const filters = [
  { label: 'All', value: 'all' }, { label: 'LOA through Ramayana', value: 'loa', course: '/courses/loa' },
  { label: 'Udyog Sanjivani', value: 'udyog-sanjivani', course: '/courses/udyog-sanjivani' },
  { label: 'Life’s Golden Triangle™', value: 'lgt', course: '/courses/lgt' }, { label: 'Corporate', value: 'corporate' }, { label: 'Events', value: 'events' },
];
const imageAlt = (item: GalleryItem) => {
  const month = item.date ? new Intl.DateTimeFormat('en-IN', { month: 'long', year: 'numeric' }).format(new Date(`${item.date}T00:00:00`)) : '';
  return [item.caption || item.event_name || 'Workshop participants', item.city, month].filter(Boolean).join(', ');
};

export default function GalleryPage() {
  const { data = [], isLoading } = useGallery();
  const [filter, setFilter] = useState('all'); const [selectedIndex, setSelectedIndex] = useState<number | null>(null); const touchStart = useRef<number | null>(null);
  const items = useMemo(() => filter === 'all' ? data : data.filter(item => filter === 'corporate' || filter === 'events' ? item.category.toLowerCase() === filter : item.program_slug === filter), [data, filter]);
  const selected = selectedIndex === null ? null : items[selectedIndex];
  const move = (direction: number) => setSelectedIndex(index => index === null || items.length === 0 ? null : (index + direction + items.length) % items.length);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (!selected) return; if (event.key === 'Escape') setSelectedIndex(null); if (event.key === 'ArrowLeft') move(-1); if (event.key === 'ArrowRight') move(1); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [selected, items.length]);
  return <div className="bg-background"><PublicSeo title="Gallery | Workshops & Events in Pune | Vivek Doba" description="Photos and videos from Vivek Doba’s workshops, seminars and coaching programs in Pune and across India." path="/gallery" schemas={[breadcrumbSchema([{ name: 'Home', path: '/' }, { name: 'Gallery', path: '/gallery' }])]} />
    <section className="border-b border-border bg-course-ivory py-14 sm:py-20"><div className="mx-auto max-w-6xl px-4"><p className="mb-3 flex items-center gap-2 text-sm font-bold uppercase tracking-widest text-primary"><ImageIcon className="h-4 w-4" /> Real moments</p><h1 className="max-w-4xl text-4xl font-bold sm:text-5xl">Gallery: Workshops, Seminars and Coaching in Pune</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">Real people, real rooms and the work of bringing Business, Health and Family back into balance.</p></div></section>
    <section className="py-12 sm:py-16"><div className="mx-auto max-w-7xl px-4"><div className="mb-9 flex gap-2 overflow-x-auto pb-3" aria-label="Filter gallery">{filters.map(item => <div key={item.value} className="shrink-0"><Button size="sm" variant={filter === item.value ? 'default' : 'outline'} onClick={() => setFilter(item.value)}>{item.label}</Button>{item.course && filter === item.value && <Link to={item.course} className="ml-2 inline-flex items-center gap-1 text-xs font-semibold text-primary">Program <ExternalLink className="h-3 w-3" /></Link>}</div>)}</div>
      {isLoading ? <p className="text-muted-foreground">Loading gallery…</p> : items.length === 0 ? <div className="border border-dashed border-primary/40 p-10 text-center"><ImageIcon className="mx-auto mb-3 h-10 w-10 text-primary" /><h2 className="text-xl font-bold">Real workshop moments coming soon</h2><p className="mt-2 text-sm text-muted-foreground">Only verified event photos and videos will appear here.</p></div> : <div className="columns-1 gap-5 sm:columns-2 lg:columns-3">{items.map((item, index) => <Button variant="ghost" key={item.id} onClick={() => setSelectedIndex(index)} className="group relative mb-5 block h-auto w-full break-inside-avoid overflow-hidden rounded-lg bg-muted p-0 text-left"><img src={item.image_url || item.thumbnail_url || `https://img.youtube.com/vi/${item.youtube_id}/hqdefault.jpg`} alt={imageAlt(item)} width="900" height={index % 3 === 1 ? 1125 : 675} loading="lazy" className={`w-full object-cover transition-transform duration-300 group-hover:scale-[1.02] ${index % 3 === 1 ? 'aspect-[4/5]' : 'aspect-[4/3]'}`} /><span className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-foreground/90 to-transparent px-4 pb-4 pt-12 text-background"><span className="block font-semibold">{item.youtube_id && <Play className="mr-1 inline h-4 w-4" />}{item.caption || item.event_name}</span>{item.city && <span className="mt-1 block text-xs text-background/80">{item.city}</span>}</span></Button>)}</div>}
    </div></section>
    {selected && <div className="fixed inset-0 z-[80] flex items-center justify-center bg-foreground/95 p-4" role="dialog" aria-modal="true" aria-label={imageAlt(selected)} onTouchStart={event => { touchStart.current = event.touches[0]?.clientX ?? null; }} onTouchEnd={event => { const end = event.changedTouches[0]?.clientX; if (touchStart.current === null || end === undefined) return; const delta = end - touchStart.current; if (Math.abs(delta) > 50) move(delta > 0 ? -1 : 1); touchStart.current = null; }}><Button size="icon" variant="secondary" aria-label="Close gallery" className="absolute right-4 top-4" onClick={() => setSelectedIndex(null)}><X /></Button>{items.length > 1 && <><Button size="icon" variant="secondary" aria-label="Previous gallery item" className="absolute left-3 top-1/2" onClick={() => move(-1)}><ChevronLeft /></Button><Button size="icon" variant="secondary" aria-label="Next gallery item" className="absolute right-3 top-1/2" onClick={() => move(1)}><ChevronRight /></Button></>}
      <figure className="w-full max-w-5xl">{selected.youtube_id ? <iframe src={`https://www.youtube-nocookie.com/embed/${selected.youtube_id}?autoplay=1`} title={imageAlt(selected)} className="aspect-video w-full" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen /> : <img src={selected.image_url || selected.media_url} alt={imageAlt(selected)} width="1600" height="1200" className="max-h-[78vh] w-full object-contain" />}<figcaption className="mt-4 text-background"><strong>{selected.caption || selected.event_name}</strong>{selected.city && <span className="ml-2 text-background/70">· {selected.city}</span>}</figcaption></figure>
    </div>}
  </div>;
}