import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, BookOpen, Check, MessageCircle, PackageCheck, Truck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useProduct } from '@/hooks/usePublicContent';
import PublicSeo, { breadcrumbSchema, SITE_URL } from '@/components/public/PublicSeo';

export default function ProductDetailPage() {
  const { slug } = useParams();
  const { data: product, isLoading } = useProduct(slug);
  const [selectedImage, setSelectedImage] = useState(0);
  if (isLoading) return <div className="min-h-[60vh] px-4 py-20 text-center text-muted-foreground">Loading product…</div>;
  if (!product) return <section className="min-h-[60vh] px-4 py-20 text-center"><h1 className="text-3xl font-bold">Product not found</h1><Button asChild variant="outline" className="mt-6"><Link to="/shop"><ArrowLeft />Back to shop</Link></Button></section>;
  const images = Array.from(new Set([product.image_url, ...(product.gallery_images || [])].filter((image): image is string => Boolean(image))));
  const orderUrl = `https://wa.me/919607050111?text=${encodeURIComponent(`Namaste, I would like to order ${product.name}.`)}`;
  const productSchema = { '@context': 'https://schema.org', '@type': 'Product', name: product.name, image: images, description: product.short_description || product.long_description, sku: product.slug, offers: { '@type': 'Offer', url: `${SITE_URL}/shop/${product.slug}`, priceCurrency: 'INR', price: Number(product.price_inr || 0), availability: product.is_preorder ? 'https://schema.org/PreOrder' : product.stock_status === 'in_stock' ? 'https://schema.org/InStock' : 'https://schema.org/OutOfStock' } };
  return <div className="bg-background">
    <PublicSeo title={`${product.name} | Vivek Doba`} description={(product.short_description || product.long_description || product.name).slice(0, 155)} path={`/shop/${product.slug}`} image={images[0]} schemas={[productSchema, breadcrumbSchema([{ name: 'Home', path: '/' }, { name: 'Shop', path: '/shop' }, { name: product.name, path: `/shop/${product.slug}` }])]} />
    <section className="py-10 sm:py-16"><div className="mx-auto max-w-7xl px-4"><Link to="/shop" className="mb-8 inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="h-4 w-4" />Back to shop</Link><div className="grid gap-10 lg:grid-cols-2">
      <div><div className="overflow-hidden rounded-lg border border-border bg-muted">{images[selectedImage] ? <img src={images[selectedImage]} alt={`${product.name} view ${selectedImage + 1}`} width="1000" height="1000" className="aspect-square w-full object-cover" /> : <div className="flex aspect-square items-center justify-center"><BookOpen className="h-20 w-20 text-primary/40" /></div>}</div>{images.length > 1 && <div className="mt-4 grid grid-cols-4 gap-3">{images.map((image, index) => <button key={image} type="button" onClick={() => setSelectedImage(index)} aria-label={`View product image ${index + 1}`} className={`overflow-hidden rounded-md border-2 ${selectedImage === index ? 'border-primary' : 'border-border'}`}><img src={image} alt="" width="240" height="240" loading="lazy" className="aspect-square w-full object-cover" /></button>)}</div>}</div>
      <div><p className="mb-3 flex items-center gap-2 text-sm font-bold uppercase tracking-widest text-primary"><PackageCheck className="h-4 w-4" />{product.is_preorder ? 'Pre-order' : product.stock_status.replace(/_/g, ' ')}</p><h1 className="text-4xl font-bold leading-tight sm:text-5xl">{product.name}</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">{product.long_description}</p><div className="mt-7 border-y border-border py-6"><p className="text-3xl font-bold text-course-maroon">₹{Number(product.price_inr || 0).toLocaleString('en-IN')}</p><p className="mt-1 text-sm text-muted-foreground">{product.gst_included ? 'Inclusive of all taxes' : '+ applicable taxes'}</p></div><Button asChild size="lg" className="mt-7 w-full bg-course-saffron text-primary-foreground hover:bg-course-saffron/90 sm:w-auto"><a href={orderUrl} target="_blank" rel="noopener noreferrer">{product.is_preorder ? 'Pre-book' : 'Buy'} <MessageCircle /></a></Button></div>
    </div></div></section>
    <section className="border-y border-border bg-muted/40 py-14 sm:py-16"><div className="mx-auto grid max-w-6xl gap-8 px-4 md:grid-cols-3"><article><BookOpen className="h-7 w-7 text-primary" /><h2 className="mt-4 text-xl font-bold">What is inside</h2><ul className="mt-4 space-y-3 text-muted-foreground"><li className="flex gap-2"><Check className="mt-1 h-4 w-4 shrink-0 text-primary" />Life’s Golden Triangle book</li><li className="flex gap-2"><Check className="mt-1 h-4 w-4 shrink-0 text-primary" />Companion workbook</li></ul></article><article><Check className="h-7 w-7 text-primary" /><h2 className="mt-4 text-xl font-bold">Who it is for</h2><p className="mt-4 leading-7 text-muted-foreground">Anyone who wants to begin the Life’s Golden Triangle journey at home.</p></article><article><Truck className="h-7 w-7 text-primary" /><h2 className="mt-4 text-xl font-bold">Delivery information</h2><p className="mt-4 leading-7 text-muted-foreground">[ADD DELIVERY DETAILS]</p></article></div></section>
    <section className="py-14 sm:py-16"><div className="mx-auto max-w-3xl px-4"><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-7 divide-y divide-border border-y border-border"><div className="py-5"><h3 className="font-bold">Is tax included?</h3><p className="mt-2 text-muted-foreground">{product.gst_included ? 'Yes. The displayed price is inclusive of all taxes.' : 'Applicable taxes are added separately.'}</p></div><div className="py-5"><h3 className="font-bold">When will pre-orders be available?</h3><p className="mt-2 text-muted-foreground">Founder’s Edition for the first 200 · Launching on Dussehra.</p></div><div className="py-5"><h3 className="font-bold">How do I order?</h3><p className="mt-2 text-muted-foreground">Use the WhatsApp button and our team will help you complete your order.</p></div></div></div></section>
  </div>;
}