import { useMemo, useState } from 'react';
import { Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import PageBanner from '@/components/public/PageBanner';
import { useProducts, type Product } from '@/hooks/usePublicContent';
import { Button } from '@/components/ui/button';

export default function ShopPage() {
  const { data = [], isLoading } = useProducts();
  const [cart, setCart] = useState<Record<string, number>>({});
  const total = useMemo(() => data.reduce((sum, product) => sum + Number(product.price) * (cart[product.id] || 0), 0), [cart, data]);
  const change = (product: Product, amount: number) => setCart(current => ({ ...current, [product.id]: Math.max(0, (current[product.id] || 0) + amount) }));
  const checkout = () => {
    const lines = data.filter(product => cart[product.id]).map(product => `• ${product.name} × ${cart[product.id]} — ₹${(Number(product.price) * cart[product.id]).toLocaleString('en-IN')}`);
    const text = `Namaste, I would like to order:\n${lines.join('\n')}\n\nTotal: ₹${total.toLocaleString('en-IN')}`;
    window.open(`https://wa.me/919607050111?text=${encodeURIComponent(text)}`, '_blank', 'noopener,noreferrer');
  };
  return <><PageBanner icon={ShoppingBag} eyebrow="Shop" title="Tools for your journey" description="Books, learning resources and meaningful products selected to support your transformation." />
    <section className="max-w-7xl mx-auto px-4 py-14"><div className="grid lg:grid-cols-[1fr_320px] gap-8"><div>{isLoading ? <p className="text-muted-foreground">Loading products…</p> : data.length === 0 ? <div className="border border-dashed border-primary/40 p-10 text-center"><ShoppingBag className="w-10 h-10 text-primary mx-auto mb-3" /><h2 className="text-xl font-bold">The shop is being prepared</h2><p className="text-sm text-muted-foreground mt-2">Placeholder: products added by the admin will appear here.</p></div> : <div className="grid sm:grid-cols-2 gap-5">{data.map(product => <article key={product.id} className="bg-card border border-border rounded-lg overflow-hidden">{product.image_url ? <img src={product.image_url} alt="" className="aspect-square w-full object-cover" /> : <div className="aspect-square bg-muted flex items-center justify-center"><ShoppingBag className="w-12 h-12 text-primary/50" /></div>}<div className="p-5"><span className="text-xs uppercase text-primary font-semibold">{product.category}</span><h2 className="text-lg font-bold mt-1">{product.name}</h2><p className="text-sm text-muted-foreground my-2">{product.description || 'Product details will be added soon.'}</p><div className="flex items-center justify-between mt-4"><strong>₹{Number(product.price).toLocaleString('en-IN')}</strong><Button size="sm" onClick={() => change(product, 1)}><Plus className="w-4 h-4 mr-1" />Add to Cart</Button></div></div></article>)}</div>}</div><aside className="bg-card border border-border rounded-lg p-5 h-fit lg:sticky lg:top-36"><h2 className="font-bold flex items-center gap-2"><ShoppingBag className="w-5 h-5 text-primary" />Your Cart</h2><div className="my-5 space-y-4">{data.filter(product => cart[product.id]).map(product => <div key={product.id} className="text-sm"><div className="flex justify-between gap-2"><span>{product.name}</span><button aria-label={`Remove ${product.name}`} onClick={() => setCart(c => ({ ...c, [product.id]: 0 }))}><Trash2 className="w-4 h-4 text-destructive" /></button></div><div className="flex items-center gap-2 mt-2"><Button size="icon" variant="outline" className="w-7 h-7" onClick={() => change(product, -1)}><Minus className="w-3 h-3" /></Button><span>{cart[product.id]}</span><Button size="icon" variant="outline" className="w-7 h-7" onClick={() => change(product, 1)}><Plus className="w-3 h-3" /></Button></div></div>)}{total === 0 && <p className="text-sm text-muted-foreground">Your cart is empty.</p>}</div><div className="border-t border-border pt-4 flex justify-between font-bold"><span>Total</span><span>₹{total.toLocaleString('en-IN')}</span></div><Button className="w-full mt-4 bg-[hsl(var(--dharma-green))] hover:opacity-90" disabled={total === 0} onClick={checkout}>Checkout on WhatsApp</Button></aside></div></section></>;
}